---
# Playbook para instalar e configurar uma instancia wordpress
  - hosts: prod
    gather_facts: False
    become: yes
  
    tasks:
      - name: "Atualizando o apt-cache"
        apt: update_cache=yes cache_valid_time=3600
        become: yes
        
      - name: "Instalando o Python3"
        command: apt install python3
        become: yes
        vars:
          ansible_python_interpreter: /usr/bin/python3

  - hosts: wordpress
    roles:
      - server