---
  - name: "Baixando o WordPress"
    get_url:
      url=https://wordpress.org/latest.tar.gz
      dest=/tmp/latest.tar.gz
      validate_certs=no
    tags:
      - get-wp
  
  - name: "Extraindo os arquivos..."
    unarchive:
      src=/tmp/latest.tar.gz
      dest=/var/www/
      copy=no
    become: yes
    tags:
      - unzip-wp